#define YY_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prob.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prob.y"

    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    #include "y.tab.h"
    #define SIZE 100
    #define TABLE_SIZE 100
    int yyerror(char*);
    extern FILE* yyin;
    int eflag = 0;  // Error flag for certain expressions
    extern int yylex();
    int yydebug = 0;
    int wentInArray=0;
    int blockVar =0;
    int IFCOUNTER=0;
    int tempVar=0;
    int ifStmntPtr=0;
    int lineNumber=1;
    char* array;
    char* type;
    typedef struct Node {
        char *key;
        char *value;
        struct Node *next;
    } Node;

    // Hash map structure
    typedef struct HashMap {
        Node *table[TABLE_SIZE];
        int size;
    } HashMap;

    // Stack node definition
    typedef struct StackNode {
        HashMap *map;
        struct StackNode *next;
    } StackNode;

    // Stack structure
    typedef struct Stack {
        StackNode *top;
        int size;
    } Stack;
    // Free all memory used by the hash map
        void free_hashmap(HashMap *map) {
        if (map == NULL) return;
        for (int i = 0; i < TABLE_SIZE; i++) {
            Node *current = map->table[i];
            while (current != NULL) {
                Node *temp = current;
                current = current->next;
                free(temp->key);
                free(temp->value);
                free(temp);
            }
            map->table[i] = NULL;  // Nullify after free
        }
        free(map);
        }

    // Hash function for strings
    unsigned int hash(const char *key) {
        unsigned long int hash_value = 0;
        int i = 0;

        while (key[i] != '\0') {
            hash_value = hash_value * 37 + key[i];
            i++;
        }

        return hash_value % TABLE_SIZE;
    }

    // Initialize hash map
    HashMap* create_hashmap() {
        HashMap *map = (HashMap *)malloc(sizeof(HashMap));
        if (!map) {
            fprintf(stderr, "Memory allocation failed\n");
            return NULL;
        }
        for (int i = 0; i < TABLE_SIZE; i++) {
            map->table[i] = NULL;
        }
        map->size = 0;
        return map;
    }

    // Create a new node for the hash map
    Node *create_node(const char *key, const char *value) {
        Node *new_node = (Node *)malloc(sizeof(Node));
        new_node->key = strdup(key);      // Copy key string
        new_node->value = strdup(value);  // Copy value string
        new_node->next = NULL;
        return new_node;
    }

    // Insert a key-value pair into the hash map
    void insert(HashMap *map,char *key, char *value) {
        unsigned int index = hash(key);
        Node *new_node = create_node(key, value);
        new_node->next = map->table[index];
        map->table[index] = new_node;
        map->size++;
    }

    // Search for a value by key in the hash map
    char *search(HashMap *map, const char *key) {
        unsigned int index = hash(key);
        Node *current = map->table[index];

        while (current != NULL) {
            if (strcmp(current->key, key) == 0) {
                return current->value;
            }
            current = current->next;
        }

        return NULL;  // Key not found
    }

    // Delete a key-value pair from the hash map
    void delete_key(HashMap *map, const char *key) {
        unsigned int index = hash(key);
        Node *current = map->table[index];
        Node *prev = NULL;

        while (current != NULL && strcmp(current->key, key) != 0) {
            prev = current;
            current = current->next;
        }

        if (current == NULL) return;  // Key not found

        if (prev == NULL) {  // Key is in the first node
            map->table[index] = current->next;
        } else {
            prev->next = current->next;
        }
        map->size--;
        free(current->key);
        free(current->value);
        free(current);
    }



    // Function to create a new stack
    Stack *create_stack() {
        Stack *stack = (Stack *)malloc(sizeof(Stack));
        stack->top = NULL;
        stack->size = 0;
        return stack;
    }

    // Push a hash map onto the stack
    void push(Stack *stack, HashMap *map) {
        StackNode *new_node = (StackNode *)malloc(sizeof(StackNode));
        new_node->map = map;
        new_node->next = stack->top;
        stack->top = new_node;
        stack->size++;
    }

    // Pop a hash map from the stack
    HashMap *pop(Stack *stack) {
        if (stack->top == NULL) {
            printf("Stack is empty!\n");
            return NULL;
        }

        StackNode *top_node = stack->top;
        HashMap *map = top_node->map;
        stack->top = top_node->next;
        free(top_node);
        stack->size--;
        return map;
    }

    // Peek at the top hash map without removing it
    HashMap *peek(Stack *stack) {
        if (stack->top == NULL) {
            printf("Stack is empty!\n");
            return NULL;
        }
        return stack->top->map;
    }

    // Check if the stack is empty
    int is_empty(Stack *stack) {
        return stack->top == NULL;
    }

    // Free the entire stack
    void free_stack(Stack *stack) {
        while (!is_empty(stack)) {
            HashMap *map = pop(stack);
            free_hashmap(map);  // Free each hash map in the stack
        }
        free(stack);
    }

    char* getLabels()
    {
        char* tVar = (char*)malloc(10*sizeof(char));
        snprintf(tVar,10,"t%d",tempVar++);
        return tVar;
    }
    void handleClear(int val)
    {
        lineNumber=1;
        ifStmntPtr=0;
        if(val)
        {
            tempVar=0;
            blockVar=0;
        }
    }

    Stack* globStack;
    HashMap* currMap;

    void checkDeclaration(char* var, int newDecl)
    {
        Stack* tempStack = create_stack();
        while(!is_empty(globStack) && (search(currMap,var)==NULL))
        {
            push(tempStack, currMap);
            currMap = pop(globStack);
        }
        if((search(currMap,var)==NULL))
        {
            if(newDecl==0)
            {
                printf("Variable %s not declared in all scopes\n",var);
                printf("I will add it anyways... sob sob weep weep\n");
            }
        }
        else if(newDecl)
        {
            char* val = search(currMap, var);
            printf("Error -> Redeclartion of variable %s!!\n",var);
            if(strcmp(val,type) !=0)
            {
                printf("Error -> Change of Type of variable %s!!\n",var);
                printf("I am a good compiler so I will change its type just like python\n");
                delete_key(currMap,var);
            }
        }
        push(globStack,currMap);//put the currMap back...
        while(!is_empty(tempStack))
        {
            push(globStack,pop(tempStack));
        } 
        currMap = pop(globStack);//push in currMap...
        printf("%s type -> %s\n",var,type);
        array = strdup(var);
        insert(currMap,strdup(var),strdup(type));
        free_stack(tempStack);
    }


#line 264 "prob.y"
typedef union {
    char* str;
} yy_parser_stype;
#define YY_parser_STYPE yy_parser_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_BISON 1

#ifndef YY_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_COMPATIBILITY 1
 #else
  #define  YY_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_LTYPE
   #define YY_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_STYPE 
   #define YY_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_DEBUG
   #define  YY_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_USE_GOTO
  #define YY_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_USE_GOTO
 #define YY_parser_USE_GOTO 0
#endif

#ifndef YY_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parser_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_DEBUG */
#endif


#ifndef YY_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_LSP_NEEDED
#ifndef YY_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_STYPE
#define YY_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_PARSE
#define YY_parser_PARSE yyparse
#endif
#ifndef YY_parser_LEX
#define YY_parser_LEX yylex
#endif
#ifndef YY_parser_LVAL
#define YY_parser_LVAL yylval
#endif
#ifndef YY_parser_LLOC
#define YY_parser_LLOC yylloc
#endif
#ifndef YY_parser_CHAR
#define YY_parser_CHAR yychar
#endif
#ifndef YY_parser_NERRS
#define YY_parser_NERRS yynerrs
#endif
#ifndef YY_parser_DEBUG_FLAG
#define YY_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_ERROR
#define YY_parser_ERROR yyerror
#endif

#ifndef YY_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_PARSE_PARAM
  #define YY_parser_PARSE_PARAM void
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_PURE
#  endif
#endif

#ifdef YY_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_DEBUG 
#  endif
#endif

#ifndef YY_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	VAR	258
#define	Floats	259
#define	ASSIGN	260
#define	SC	261
#define	LP	262
#define	RP	263
#define	CL	264
#define	CR	265
#define	INC	266
#define	RELOP	267
#define	Else	268
#define	DEC	269
#define	Int	270
#define	If	271
#define	While	272
#define	BoolAnd	273
#define	BoolOr	274
#define	Float	275
#define	Char	276
#define	COMMA	277
#define	arrRP	278
#define	arrLP	279


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_CLASS
#define YY_parser_CLASS parser
#endif
#ifndef YY_parser_INHERIT
#define YY_parser_INHERIT
#endif
#ifndef YY_parser_MEMBERS
#define YY_parser_MEMBERS 
#endif
#ifndef YY_parser_LEX_BODY
#define YY_parser_LEX_BODY  
#endif
#ifndef YY_parser_ERROR_BODY
#define YY_parser_ERROR_BODY  
#endif
#ifndef YY_parser_CONSTRUCTOR_PARAM
#define YY_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_CONSTRUCTOR_CODE
#define YY_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_CONSTRUCTOR_INIT
#define YY_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_USE_CONST_TOKEN
#define YY_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_USE_CONST_TOKEN != 0
#ifndef YY_parser_ENUM_TOKEN
#define YY_parser_ENUM_TOKEN yy_parser_enum_token
#endif
#endif

class YY_parser_CLASS YY_parser_INHERIT
{
public: 
#if YY_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int VAR;
static const int Floats;
static const int ASSIGN;
static const int SC;
static const int LP;
static const int RP;
static const int CL;
static const int CR;
static const int INC;
static const int RELOP;
static const int Else;
static const int DEC;
static const int Int;
static const int If;
static const int While;
static const int BoolAnd;
static const int BoolOr;
static const int Float;
static const int Char;
static const int COMMA;
static const int arrRP;
static const int arrLP;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_ENUM_TOKEN { YY_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,VAR=258
	,Floats=259
	,ASSIGN=260
	,SC=261
	,LP=262
	,RP=263
	,CL=264
	,CR=265
	,INC=266
	,RELOP=267
	,Else=268
	,DEC=269
	,Int=270
	,If=271
	,While=272
	,BoolAnd=273
	,BoolOr=274
	,Float=275
	,Char=276
	,COMMA=277
	,arrRP=278
	,arrLP=279


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_PARSE (YY_parser_PARSE_PARAM);
 virtual void YY_parser_ERROR(char *msg) YY_parser_ERROR_BODY;
#ifdef YY_parser_PURE
#ifdef YY_parser_LSP_NEEDED
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL,YY_parser_LTYPE *YY_parser_LLOC) YY_parser_LEX_BODY;
#else
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL) YY_parser_LEX_BODY;
#endif
#else
 virtual int YY_parser_LEX() YY_parser_LEX_BODY;
 YY_parser_STYPE YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
 YY_parser_LTYPE YY_parser_LLOC;
#endif
 int   YY_parser_NERRS;
 int    YY_parser_CHAR;
#endif
#if YY_parser_DEBUG != 0
 int YY_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM);
public:
 YY_parser_MEMBERS 
};
/* other declare folow */
#if YY_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_CLASS::VAR=258;
const int YY_parser_CLASS::Floats=259;
const int YY_parser_CLASS::ASSIGN=260;
const int YY_parser_CLASS::SC=261;
const int YY_parser_CLASS::LP=262;
const int YY_parser_CLASS::RP=263;
const int YY_parser_CLASS::CL=264;
const int YY_parser_CLASS::CR=265;
const int YY_parser_CLASS::INC=266;
const int YY_parser_CLASS::RELOP=267;
const int YY_parser_CLASS::Else=268;
const int YY_parser_CLASS::DEC=269;
const int YY_parser_CLASS::Int=270;
const int YY_parser_CLASS::If=271;
const int YY_parser_CLASS::While=272;
const int YY_parser_CLASS::BoolAnd=273;
const int YY_parser_CLASS::BoolOr=274;
const int YY_parser_CLASS::Float=275;
const int YY_parser_CLASS::Char=276;
const int YY_parser_CLASS::COMMA=277;
const int YY_parser_CLASS::arrRP=278;
const int YY_parser_CLASS::arrLP=279;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_CLASS::token */
#endif
/*apres const  */
YY_parser_CLASS::YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM) YY_parser_CONSTRUCTOR_INIT
{
#if YY_parser_DEBUG != 0
YY_parser_DEBUG_FLAG=0;
#endif
YY_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		155
#define	YYFLAG		-32768
#define	YYNTBASE	34

#define YYTRANSLATE(x) ((unsigned)(x) <= 279 ? yytranslate[x] : 60)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    33,     2,     2,     2,    32,    27,     2,     2,
     2,    30,    28,     2,    29,     2,    31,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    26,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    25,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24
};

#if YY_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     5,     6,    10,    11,    15,    16,    20,    21,
    22,    29,    30,    32,    34,    36,    38,    42,    46,    47,
    51,    52,    53,    64,    69,    76,    81,    82,    83,    92,
    97,   107,   111,   113,   116,   120,   124,   129,   135,   139,
   143,   147,   151,   154,   156,   158,   160,   162,   164,   168,
   172,   176,   180,   184,   188,   191,   193,   196,   199,   202,
   205,   206,   210,   213,   217,   221,   225,   229,   233,   237,
   239,   242,   245,   250
};

static const short yyrhs[] = {    -1,
    46,    35,    34,     0,     0,    53,    36,    34,     0,     0,
    50,    37,    34,     0,     0,    43,    38,    34,     0,     0,
     0,     9,    39,    34,    10,    40,    34,     0,     0,    15,
     0,    20,     0,    21,     0,    41,     0,    42,    44,     6,
     0,    44,    22,     3,     0,     0,     3,    45,    58,     0,
     0,     0,    16,     7,    52,     8,     9,    47,    34,    10,
    48,    49,     0,    16,    52,     1,    10,     0,    16,     7,
    52,     9,     1,    10,     0,    13,     9,    34,    10,     0,
     0,     0,    17,     7,    52,     8,     9,    51,    34,    10,
     0,    17,    52,     1,    10,     0,    17,     7,    52,     9,
     1,    13,     9,    34,    10,     0,    55,    12,    55,     0,
    53,     0,    33,    55,     0,    52,    18,    52,     0,    52,
    19,    52,     0,     3,     5,    55,     6,     0,    42,     3,
     5,    55,     6,     0,     3,    11,     6,     0,     3,    14,
     6,     0,    11,     3,     6,     0,    14,     3,     6,     0,
     1,     6,     0,    28,     0,    29,     0,    31,     0,    32,
     0,    30,     0,    55,    28,    55,     0,    55,    29,    55,
     0,    55,    26,    55,     0,    55,    30,    55,     0,    55,
    31,    55,     0,    55,    32,    55,     0,    55,    54,     0,
    56,     0,     3,    11,     0,     3,    14,     0,    11,     3,
     0,    14,     3,     0,     0,     3,    57,    58,     0,     4,
    58,     0,     4,    11,     1,     0,     4,    14,     1,     0,
    14,     4,     1,     0,    11,     4,     1,     0,     7,    55,
     8,     0,     7,    55,     1,     0,    59,     0,     3,     1,
     0,     4,     1,     0,    24,     4,    23,    59,     0,     0
};

#endif

#if (YY_parser_DEBUG != 0) || defined(YY_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   284,   312,   312,   315,   315,   318,   318,   322,   322,   325,
   336,   336,   339,   344,   348,   354,   358,   364,   368,   371,
   372,   379,   383,   383,   393,   405,   407,   410,   417,   421,
   431,   443,   449,   450,   455,   460,   467,   476,   485,   493,
   500,   507,   514,   523,   523,   523,   523,   523,   525,   532,
   539,   546,   553,   560,   573,   578,   584,   591,   598,   605,
   612,   619,   619,   625,   633,   641,   649,   657,   661,   671,
   678,   687,   698,   756
};

static const char * const yytname[] = {   "$","error","$illegal.","VAR","Floats",
"ASSIGN","SC","LP","RP","CL","CR","INC","RELOP","Else","DEC","Int","If","While",
"BoolAnd","BoolOr","Float","Char","COMMA","arrRP","arrLP","'|'","'^'","'&'",
"'+'","'-'","'*'","'/'","'%'","'!'","S","@1","@2","@3","@4","@5","@6","DeclType",
"TypeDecl","VarDecl","L","@7","IfStatement","@8","@9","ElseExpr","WhileStatements",
"@10","BoolExp","Assignments","Op","Expr","Fact","@11","C","Arrays",""
};
#endif

static const short yyr1[] = {     0,
    35,    34,    36,    34,    37,    34,    38,    34,    39,    40,
    34,    34,    41,    41,    41,    42,    43,    44,    45,    44,
    47,    48,    46,    46,    46,    49,    49,    51,    50,    50,
    50,    52,    52,    52,    52,    52,    53,    53,    53,    53,
    53,    53,    53,    54,    54,    54,    54,    54,    55,    55,
    55,    55,    55,    55,    55,    55,    56,    56,    56,    56,
    57,    56,    56,    56,    56,    56,    56,    56,    56,    58,
    58,    58,    59,    59
};

static const short yyr2[] = {     0,
     0,     3,     0,     3,     0,     3,     0,     3,     0,     0,
     6,     0,     1,     1,     1,     1,     3,     3,     0,     3,
     0,     0,    10,     4,     6,     4,     0,     0,     8,     4,
     9,     3,     1,     2,     3,     3,     4,     5,     3,     3,
     3,     3,     2,     1,     1,     1,     1,     1,     3,     3,
     3,     3,     3,     3,     2,     1,     2,     2,     2,     2,
     0,     3,     2,     3,     3,     3,     3,     3,     3,     1,
     2,     2,     4,     0
};

static const short yydefact[] = {     0,
     0,     0,     9,     0,     0,    13,     0,     0,    14,    15,
    16,     0,     7,     1,     5,     3,    43,     0,     0,     0,
     0,     0,     0,    61,    74,     0,     0,     0,     0,     0,
     0,    33,     0,    56,     0,     0,    19,     0,     0,     0,
     0,     0,    61,     0,     0,     0,     0,    39,    40,     0,
    41,    42,    57,    58,    74,     0,     0,     0,     0,     0,
    63,    70,     0,     0,    59,     0,    60,     0,    34,     0,
     0,     0,     0,     0,     0,    44,    45,    48,    46,    47,
    55,     0,     0,     0,    74,    17,     0,     8,     2,     6,
     4,    57,    58,     0,    59,    60,    37,    10,    62,    71,
    72,    64,    65,     0,     0,     0,    69,    68,    67,    66,
    24,    35,    36,    32,    51,    49,    50,    52,    53,    54,
     0,     0,    30,     0,    20,    18,     0,    74,    21,     0,
    28,     0,    38,    11,    73,     0,    25,     0,     0,     0,
     0,     0,    22,    29,     0,    27,    31,     0,    23,     0,
     0,    26,     0,     0,     0
};

static const short yydefgoto[] = {    50,
    40,    42,    41,    39,    21,   127,    11,    12,    13,    38,
    85,    14,   136,   146,   149,    15,   138,    31,    16,    81,
    33,    34,    55,    61,    62
};

static const short yypact[] = {   196,
    15,     6,-32768,     5,    22,-32768,    75,    90,-32768,-32768,
-32768,    26,-32768,-32768,-32768,-32768,-32768,   243,    30,    60,
   217,    86,    94,    40,    95,   111,    12,    61,   243,    78,
    34,-32768,   213,-32768,   111,    37,    38,     1,   174,   174,
   174,   174,    66,   243,    69,    84,   134,-32768,-32768,    92,
-32768,-32768,    30,    60,    10,   102,   106,   112,   115,   113,
-32768,-32768,   184,    18,    86,   119,    94,   120,   150,    38,
   114,   111,   111,   243,   243,   243,   243,   243,   243,   243,
-32768,   240,   123,   243,    10,-32768,   126,-32768,-32768,-32768,
-32768,-32768,-32768,   127,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   107,   125,   136,-32768,-32768,-32768,-32768,
-32768,-32768,   121,   150,   232,    53,    53,-32768,-32768,-32768,
   132,   142,-32768,   141,-32768,-32768,   174,   122,-32768,   135,
-32768,   138,-32768,-32768,-32768,   217,-32768,   217,   139,   144,
   151,   217,-32768,-32768,   158,   173,-32768,   140,-32768,   217,
   177,-32768,   152,   198,-32768
};

static const short yypgoto[] = {     0,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    -4,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,     2,    -2,-32768,
   -17,-32768,-32768,   -53,    72
};


#define	YYLAST		264


static const short yytable[] = {   153,
    47,    99,    30,    30,    32,    32,    86,    22,    64,    36,
    18,    69,    56,    57,    65,    66,    19,    64,   107,    20,
    17,    30,    87,    32,    23,   108,    94,    63,    37,    74,
    30,   125,    32,    60,    71,    48,    82,    83,    88,    89,
    90,    91,    84,    75,    18,    76,    77,    78,    79,    80,
    53,    72,    73,    54,    72,    73,   114,   115,   116,   117,
   118,   119,   120,    67,    68,    49,   124,    30,    30,    32,
    32,    95,    66,   112,   113,     1,    92,    24,    25,    93,
    70,    26,    78,    79,    80,    27,    96,    68,    28,     6,
     1,    51,    24,    25,     9,    10,    35,    56,    57,    52,
    27,    98,   100,    28,     6,    58,   101,    29,    59,     9,
    10,     1,   102,    24,    25,   103,   104,    44,    60,   109,
   110,    27,    29,   111,    28,     6,   134,   107,   126,   128,
     9,    10,   123,   129,   108,   140,   130,   141,    72,    97,
   131,   145,   132,    29,   137,    60,   133,   142,   150,   151,
   139,   154,    75,   143,    76,    77,    78,    79,    80,    75,
   144,    76,    77,    78,    79,    80,    75,   147,    76,    77,
    78,    79,    80,   -12,     1,    75,     2,    76,    77,    78,
    79,    80,     3,   -12,     4,   148,   152,     5,     6,     7,
     8,   105,   106,     9,    10,   -12,     1,   155,     2,   135,
     0,    72,    73,     0,     3,     0,     4,     0,     0,     5,
     6,     7,     8,     0,     0,     9,    10,     1,     0,     2,
     0,     0,     0,     0,    74,     3,   -12,     4,     0,     0,
     5,     6,     7,     8,     0,     0,     9,    10,    75,     0,
    76,    77,    78,    79,    80,    43,    25,   121,   122,    44,
     0,     0,     0,    45,     0,     0,    46,    72,    73,    76,
    77,    78,    79,    80
};

static const short yycheck[] = {     0,
    18,    55,     7,     8,     7,     8,     6,     3,    26,     8,
     5,    29,     3,     4,     3,     4,    11,    35,     1,    14,
     6,    26,    22,    26,     3,     8,    44,    26,     3,    12,
    35,    85,    35,    24,     1,     6,    35,     1,    39,    40,
    41,    42,     5,    26,     5,    28,    29,    30,    31,    32,
    11,    18,    19,    14,    18,    19,    74,    75,    76,    77,
    78,    79,    80,     3,     4,     6,    84,    72,    73,    72,
    73,     3,     4,    72,    73,     1,    11,     3,     4,    14,
     3,     7,    30,    31,    32,    11,     3,     4,    14,    15,
     1,     6,     3,     4,    20,    21,     7,     3,     4,     6,
    11,    10,     1,    14,    15,    11,     1,    33,    14,    20,
    21,     1,     1,     3,     4,     1,     4,     7,    24,     1,
     1,    11,    33,    10,    14,    15,   127,     1,     3,    23,
    20,    21,    10,     9,     8,   136,     1,   138,    18,     6,
     9,   142,     1,    33,    10,    24,     6,     9,     9,   150,
    13,     0,    26,    10,    28,    29,    30,    31,    32,    26,
    10,    28,    29,    30,    31,    32,    26,    10,    28,    29,
    30,    31,    32,     0,     1,    26,     3,    28,    29,    30,
    31,    32,     9,    10,    11,    13,    10,    14,    15,    16,
    17,     8,     9,    20,    21,     0,     1,     0,     3,   128,
    -1,    18,    19,    -1,     9,    -1,    11,    -1,    -1,    14,
    15,    16,    17,    -1,    -1,    20,    21,     1,    -1,     3,
    -1,    -1,    -1,    -1,    12,     9,    10,    11,    -1,    -1,
    14,    15,    16,    17,    -1,    -1,    20,    21,    26,    -1,
    28,    29,    30,    31,    32,     3,     4,     8,     9,     7,
    -1,    -1,    -1,    11,    -1,    -1,    14,    18,    19,    28,
    29,    30,    31,    32
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_CHAR = (token), YY_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_PURE
/* UNPURE */
#define YYLEX           YY_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_CHAR;                      /*  the lookahead symbol        */
YY_parser_STYPE      YY_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_LSP_NEEDED
YY_parser_LTYPE YY_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_LSP_NEEDED
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL, &YY_parser_LLOC)
#else
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_DEBUG != 0
int YY_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_CLASS::
#endif
     YY_parser_PARSE(YY_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_LTYPE *yyls = yylsa;
  YY_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_PURE
  int YY_parser_CHAR;
  YY_parser_STYPE YY_parser_LVAL;
  int YY_parser_NERRS;
#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE YY_parser_LLOC;
#endif
#endif

  YY_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_NERRS = 0;
  YY_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_LSP_NEEDED
      YY_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_LSP_NEEDED
      yyls = (YY_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_CHAR == YYEMPTY)
    {
#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_CHAR);

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_CHAR, YY_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_CHAR != YYEOF)
    YY_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 284 "prob.y"
{ 
        if(eflag == 0) 
        {
            if(IFCOUNTER==1)
            {
                printf("\t\t Accepted!\n\n");
                printf("\nProcessing Next Input\n");
                tempVar=0;
                blockVar=0;
            }
            else
            {
                blockVar-=2;
            }
            IFCOUNTER--;
        }
        else if(eflag == 1)
        {
            printf("float not to be used with modulo symbol\n\n");
            handleClear(1);
        }
        else if( eflag==2)
        {
            printf("\t\t Operands not found\n\n");
            handleClear(1);
        }

    ;
    break;}
case 3:
#line 312 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 5:
#line 315 "prob.y"
{ 
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 7:
#line 319 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 9:
#line 322 "prob.y"
{
        push(globStack,currMap);
        currMap = create_hashmap();
    ;
    break;}
case 10:
#line 325 "prob.y"
{
        yyval.str = strdup(yyvsp[-3].str);
        if(currMap!=NULL)
        {
            free_hashmap(currMap);
        }
        if(globStack->size>0)
        {
            currMap = pop(globStack);//restore old type info...
        }
    ;
    break;}
case 12:
#line 336 "prob.y"
{;
    break;}
case 13:
#line 341 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 14:
#line 345 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 15:
#line 349 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 16:
#line 355 "prob.y"
{ type = strdup(yyvsp[0].str); ;
    break;}
case 17:
#line 359 "prob.y"
{
        yyval.str = "";
    ;
    break;}
case 18:
#line 365 "prob.y"
{
        checkDeclaration(yyvsp[0].str,1);
    ;
    break;}
case 19:
#line 368 "prob.y"
{
        checkDeclaration(yyvsp[0].str,1);
    ;
    break;}
case 21:
#line 373 "prob.y"
{
        printf("if t%d goto L%d\n goto L%d\n",tempVar-1,blockVar , blockVar+1);
        printf("L%d:\n",blockVar);
        blockVar+=2;
        IFCOUNTER++;
        handleClear(0);
    ;
    break;}
case 22:
#line 379 "prob.y"
{   
        printf("L%d:\n",blockVar-1);
        handleClear(0);
    ;
    break;}
case 24:
#line 385 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 25:
#line 395 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-3].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 26:
#line 406 "prob.y"
{;
    break;}
case 27:
#line 407 "prob.y"
{;
    break;}
case 28:
#line 411 "prob.y"
{
        printf("if t%d goto L%d\n goto L%d\n", tempVar-1,blockVar , blockVar+1); 
        printf("L%d:\n",blockVar);
        blockVar+=2;
        IFCOUNTER++;
        handleClear(0);
    ;
    break;}
case 29:
#line 417 "prob.y"
{   
        printf("goto%d:\n",blockVar-2);
        handleClear(0);
    ;
    break;}
case 30:
#line 423 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 31:
#line 433 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-6].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 32:
#line 444 "prob.y"
{
        char* Label = getLabels();
        printf("%s = (%s %s %s);\n",Label,yyvsp[-2].str,yyvsp[-1].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 33:
#line 449 "prob.y"
{;
    break;}
case 34:
#line 450 "prob.y"
{
        char* Label = getLabels();
        printf("%s = ! ( %s );\n",Label,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 35:
#line 455 "prob.y"
{
        char* Label = getLabels();
        printf("%s =  (%s && %s) ;\n",Label,yyvsp[-2].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 36:
#line 460 "prob.y"
{
        char* Label = getLabels();
        printf("%s =  (%s || %s) ;\n",Label,yyvsp[-2].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 37:
#line 469 "prob.y"
{   
        checkDeclaration(yyvsp[-3].str,0);
        char* Label = getLabels();
        printf("%s %s %s;\n",yyvsp[-3].str,yyvsp[-2].str,yyvsp[-1].str);
        printf("%s = %s;\n",Label,yyvsp[-3].str);
        yyval.str = Label;
    ;
    break;}
case 38:
#line 477 "prob.y"
{   
        checkDeclaration(yyvsp[-3].str,1);
        insert(currMap,strdup(yyvsp[-3].str),strdup(type));
        char* Label = getLabels();
        printf("%s %s %s %s;\n",type,yyvsp[-3].str,yyvsp[-2].str, yyvsp[-1].str);
        printf("%s = %s;\n",Label,yyvsp[-3].str);
        yyval.str = Label;
    ;
    break;}
case 39:
#line 486 "prob.y"
{ 
        checkDeclaration(yyvsp[-2].str,0);
        char* Label = getLabels();
        printf("%s = %s\n",Label, yyvsp[-2].str);
        printf("%s = %s + 1\n",yyvsp[-2].str, yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 40:
#line 493 "prob.y"
{ 
        checkDeclaration(yyvsp[-2].str,0);
        char* Label = getLabels();
        printf("%s = %s\n",Label, yyvsp[-2].str);
        printf("%s = %s - 1\n",yyvsp[-2].str, yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 41:
#line 500 "prob.y"
{ 
        checkDeclaration(yyvsp[-1].str,0);
        char* Label = getLabels();
        printf("%s = %s + 1\n",yyvsp[-2].str, yyvsp[-2].str);
        printf("%s = %s\n",Label, yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 42:
#line 507 "prob.y"
{ 
        checkDeclaration(yyvsp[-1].str,0);
        char* Label = getLabels();
        printf("%s = %s - 1\n",yyvsp[-2].str, yyvsp[-2].str);
        printf("%s = %s\n",Label, yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 43:
#line 514 "prob.y"
{
        yyerror("");
        printf("Missing \';\' or some syntax issue you have chanted ;) :) \n");
        yyerrok;
        yyclearin;
        handleClear(1);
    ;
    break;}
case 49:
#line 526 "prob.y"
{ 
        // Generate TAC for addition
        char* Label = getLabels();
        printf("%s = %s + %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 50:
#line 533 "prob.y"
{ 
        // Generate TAC for subtraction
        char* Label = getLabels();
        printf("%s = %s - %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 51:
#line 540 "prob.y"
{ 
        // Generate TAC for or
        char* Label = getLabels();
        printf("%s = %s ^ %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 52:
#line 547 "prob.y"
{ 
        // Generate TAC for multiplication
        char* Label = getLabels();
        printf("%s = %s * %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 53:
#line 554 "prob.y"
{   
        // Generate TAC for division
        char* Label = getLabels();
        printf("%s = %s / %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 54:
#line 561 "prob.y"
{
        if (strchr(yyvsp[-2].str, '.') == NULL && strchr(yyvsp[0].str, '.') == NULL)
        {
            char* Label = getLabels();
            printf("%s = %s \% %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
            yyval.str = Label;
        }
        else
        {
            eflag = 1;  
        }
    ;
    break;}
case 55:
#line 575 "prob.y"
{
        eflag=2;
    ;
    break;}
case 56:
#line 579 "prob.y"
{
        yyval.str = strdup(yyvsp[0].str);
    ;
    break;}
case 57:
#line 584 "prob.y"
{ 
            checkDeclaration(yyvsp[-1].str,0);
            char* Label = getLabels();
            printf("%s = %s\n",Label, yyvsp[-1].str);
            printf("%s = %s + 1\n",yyvsp[-1].str, yyvsp[-1].str);
            yyval.str = Label;
        ;
    break;}
case 58:
#line 591 "prob.y"
{ 
            checkDeclaration(yyvsp[-1].str,0);
            char* Label = getLabels();
            printf("%s = %s\n",Label, yyvsp[-1].str);
            printf("%s = %s - 1\n",yyvsp[-1].str, yyvsp[-1].str);
            yyval.str = Label;
        ;
    break;}
case 59:
#line 598 "prob.y"
{ 
            checkDeclaration(yyvsp[0].str,0);
            char* Label = getLabels();
            printf("%s = %s + 1\n",yyvsp[-1].str, yyvsp[-1].str);
            printf("%s = %s\n",Label, yyvsp[-1].str);
            yyval.str = Label;
        ;
    break;}
case 60:
#line 605 "prob.y"
{ 
            checkDeclaration(yyvsp[0].str,0);
            char* Label = getLabels();
            printf("%s = %s - 1\n",yyvsp[-1].str, yyvsp[-1].str);
            printf("%s = %s\n",Label, yyvsp[-1].str);
            yyval.str = Label;
        ;
    break;}
case 61:
#line 612 "prob.y"
{ 
            checkDeclaration(yyvsp[0].str,0);
            char* Label = getLabels();
            printf("%s = %s;\n",Label,yyvsp[0].str); 
            yyval.str = Label;
            array = strdup(yyvsp[0].str);
        ;
    break;}
case 63:
#line 619 "prob.y"
{ 
            char* Label = getLabels();
            printf("%s = %s;\n",Label,yyvsp[-1].str); 
            yyval.str = Label;
            array = NULL;
        ;
    break;}
case 64:
#line 626 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 65:
#line 634 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 66:
#line 642 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 67:
#line 650 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 68:
#line 658 "prob.y"
{ 
            yyval.str = strdup(yyvsp[-1].str); 
        ;
    break;}
case 69:
#line 662 "prob.y"
{
            yyerror("");
            printf("\t\tno ) detected after (\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 70:
#line 672 "prob.y"
{
            if(wentInArray)
            {
                printf("%s %s\n",array,yyvsp[0].str);
            }
        ;
    break;}
case 71:
#line 680 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 72:
#line 689 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 73:
#line 699 "prob.y"
{
            // Copy the original number
            if(array == NULL)
            {
                printf("Error -> Please dont use array operations with floats...!!!\n");
                yyval.str = "";
            }
            else{
                wentInArray = 1;
                char* number = strdup(yyvsp[-2].str);
                if (number == NULL) {
                    printf("Error: Memory allocation failed for 'number'.\n");
                    YYABORT; // or handle error
                }

                if (strchr(number, '.') != NULL) {
                    printf("Error: Using floats as array indices is not allowed!\nTruncating...to integer..\n");

                    // Find the position of the decimal point
                    char* dot_position = strchr(number, '.');
                    int int_part_length = dot_position - number;

                    // Allocate memory for the integer part
                    char* integer_part = (char*)malloc(int_part_length + 1);
                    if (integer_part != NULL) {
                        strncpy(integer_part, number, int_part_length);
                        integer_part[int_part_length] = '\0';

                        // Free original number and assign integer_part to number
                        free(number);
                        number = integer_part;
                    } else {
                        // On memory allocation failure, set number to "0"
                        free(number);
                        number = strdup("0");
                        if (number == NULL) {
                            printf("Error: Memory allocation failed for '0'.\n");
                            YYABORT;
                        }
                    }
                }

                // Create the output string
                char* sending = (char*)malloc(20000);
                if (sending != NULL) {
                    sprintf(sending, "array(%s , %s)", number, yyvsp[0].str);
                    yyval.str = sending;
                } else {
                    printf("Error: Memory allocation failed for 'sending'.\n");
                    yyval.str = NULL;
                    YYABORT;
                }
                // Clean up
                free(number);    
            }
            
        ;
    break;}
case 74:
#line 756 "prob.y"
{
            yyval.str = strdup("");
        ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_LLOC.first_line;
      yylsp->first_column = YY_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_NERRS;

#ifdef YY_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_ERROR_VERBOSE */
	YY_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_CHAR == YYEOF)
	YYABORT;

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_CHAR, yytname[yychar1]);
#endif

      YY_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 761 "prob.y"

int yyerror(char* err) {
    return 0;
}

int main(int argc, char* argv[]) {
    int yydebug = 1;
    globStack = create_stack();
    currMap = create_hashmap();
    handleClear(1);
    // Rest of the main function
    if (argc > 1) {
        FILE* inp = fopen(argv[1], "r");
        if (inp != NULL) {
            yyin = inp;
        } else {
            fprintf(stderr, "Failed to open file: %s\n", argv[1]);
            return 1;
        }
    }
    yyparse();
    free_stack(globStack);
    fclose(yyin);

    //handleClear(1); // Clean up before exiting
    return 0;
}
