#define YY_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prob.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prob.y"

    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    #include "y.tab.h"
    #define SIZE 100
    int yyerror(char*);
    extern FILE* yyin;
    int eflag = 0;  // Error flag for certain expressions
    extern int yylex();
    int yydebug = 0;
    
    typedef struct list 
    {
        int addr;
        char* val;
        struct node* tlist;
        struct node* flist;
    } List;
    
    typedef struct Node
    {
        int indx;
        struct Node* next;
    } node;

    char** interMedCode;
    int instrPtr=0;
    int tempVar=0;
    int lineNumber=1;
    char* getLabels()
    {
        char* tVar = (char*)malloc(10*sizeof(char));
        snprintf(tVar,10,"t%d",tempVar++);
        return tVar;
    }
    void handleClear(int val)
    {
        for(int i=0;i<1000;i++)
        {
            if(interMedCode[i]!=NULL)
            {
                free(interMedCode[i]);
            }
            interMedCode[i] = (char*)malloc(100*sizeof(char));
        }
        lineNumber=1;
    }
    void BackPatch(List* patchlist,int addr)
    {   
        node* head = patchlist;
        while(head!=NULL)
        {
            snprintf(interMedCode[head->indx] + strlen(interMedCode[head->indx]) , " %d",addr);
            head = head->next;
        }
    }

#line 60 "prob.y"
typedef union {
    char* str;
    struct list * list;
} yy_parser_stype;
#define YY_parser_STYPE yy_parser_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_BISON 1

#ifndef YY_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_COMPATIBILITY 1
 #else
  #define  YY_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_LTYPE
   #define YY_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_STYPE 
   #define YY_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_DEBUG
   #define  YY_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_USE_GOTO
  #define YY_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_USE_GOTO
 #define YY_parser_USE_GOTO 0
#endif

#ifndef YY_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parser_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_DEBUG */
#endif


#ifndef YY_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_LSP_NEEDED
#ifndef YY_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_STYPE
#define YY_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_PARSE
#define YY_parser_PARSE yyparse
#endif
#ifndef YY_parser_LEX
#define YY_parser_LEX yylex
#endif
#ifndef YY_parser_LVAL
#define YY_parser_LVAL yylval
#endif
#ifndef YY_parser_LLOC
#define YY_parser_LLOC yylloc
#endif
#ifndef YY_parser_CHAR
#define YY_parser_CHAR yychar
#endif
#ifndef YY_parser_NERRS
#define YY_parser_NERRS yynerrs
#endif
#ifndef YY_parser_DEBUG_FLAG
#define YY_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_ERROR
#define YY_parser_ERROR yyerror
#endif

#ifndef YY_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_PARSE_PARAM
  #define YY_parser_PARSE_PARAM void
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_PURE
#  endif
#endif

#ifdef YY_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_DEBUG 
#  endif
#endif

#ifndef YY_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	VAR	258
#define	Floats	259
#define	ASSIGN	260
#define	SC	261
#define	LP	262
#define	RP	263
#define	CL	264
#define	CR	265
#define	INC	266
#define	RELOP	267
#define	Else	268
#define	DEC	269
#define	If	270
#define	While	271
#define	BoolAnd	272
#define	BoolOr	273


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_CLASS
#define YY_parser_CLASS parser
#endif
#ifndef YY_parser_INHERIT
#define YY_parser_INHERIT
#endif
#ifndef YY_parser_MEMBERS
#define YY_parser_MEMBERS 
#endif
#ifndef YY_parser_LEX_BODY
#define YY_parser_LEX_BODY  
#endif
#ifndef YY_parser_ERROR_BODY
#define YY_parser_ERROR_BODY  
#endif
#ifndef YY_parser_CONSTRUCTOR_PARAM
#define YY_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_CONSTRUCTOR_CODE
#define YY_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_CONSTRUCTOR_INIT
#define YY_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_USE_CONST_TOKEN
#define YY_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_USE_CONST_TOKEN != 0
#ifndef YY_parser_ENUM_TOKEN
#define YY_parser_ENUM_TOKEN yy_parser_enum_token
#endif
#endif

class YY_parser_CLASS YY_parser_INHERIT
{
public: 
#if YY_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int VAR;
static const int Floats;
static const int ASSIGN;
static const int SC;
static const int LP;
static const int RP;
static const int CL;
static const int CR;
static const int INC;
static const int RELOP;
static const int Else;
static const int DEC;
static const int If;
static const int While;
static const int BoolAnd;
static const int BoolOr;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_ENUM_TOKEN { YY_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,VAR=258
	,Floats=259
	,ASSIGN=260
	,SC=261
	,LP=262
	,RP=263
	,CL=264
	,CR=265
	,INC=266
	,RELOP=267
	,Else=268
	,DEC=269
	,If=270
	,While=271
	,BoolAnd=272
	,BoolOr=273


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_PARSE (YY_parser_PARSE_PARAM);
 virtual void YY_parser_ERROR(char *msg) YY_parser_ERROR_BODY;
#ifdef YY_parser_PURE
#ifdef YY_parser_LSP_NEEDED
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL,YY_parser_LTYPE *YY_parser_LLOC) YY_parser_LEX_BODY;
#else
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL) YY_parser_LEX_BODY;
#endif
#else
 virtual int YY_parser_LEX() YY_parser_LEX_BODY;
 YY_parser_STYPE YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
 YY_parser_LTYPE YY_parser_LLOC;
#endif
 int   YY_parser_NERRS;
 int    YY_parser_CHAR;
#endif
#if YY_parser_DEBUG != 0
 int YY_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM);
public:
 YY_parser_MEMBERS 
};
/* other declare folow */
#if YY_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_CLASS::VAR=258;
const int YY_parser_CLASS::Floats=259;
const int YY_parser_CLASS::ASSIGN=260;
const int YY_parser_CLASS::SC=261;
const int YY_parser_CLASS::LP=262;
const int YY_parser_CLASS::RP=263;
const int YY_parser_CLASS::CL=264;
const int YY_parser_CLASS::CR=265;
const int YY_parser_CLASS::INC=266;
const int YY_parser_CLASS::RELOP=267;
const int YY_parser_CLASS::Else=268;
const int YY_parser_CLASS::DEC=269;
const int YY_parser_CLASS::If=270;
const int YY_parser_CLASS::While=271;
const int YY_parser_CLASS::BoolAnd=272;
const int YY_parser_CLASS::BoolOr=273;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_CLASS::token */
#endif
/*apres const  */
YY_parser_CLASS::YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM) YY_parser_CONSTRUCTOR_INIT
{
#if YY_parser_DEBUG != 0
YY_parser_DEBUG_FLAG=0;
#endif
YY_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		121
#define	YYFLAG		-32768
#define	YYNTBASE	28

#define YYTRANSLATE(x) ((unsigned)(x) <= 273 ? yytranslate[x] : 39)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    27,     2,     2,     2,    26,    21,     2,     2,
     2,    24,    22,     2,    23,     2,    25,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    20,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    19,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18
};

#if YY_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     4,     8,    12,    13,    14,    25,    30,    37,    43,
    44,    54,    59,    69,    73,    75,    78,    82,    86,    89,
    94,    98,   102,   106,   110,   112,   114,   116,   118,   120,
   122,   126,   130,   134,   138,   142,   146,   149,   151,   154,
   157,   160,   163,   166,   169,   173,   177,   181,   185,   189,
   193,   196,   199
};

static const short yyrhs[] = {    28,
    29,    30,     0,    28,    29,    34,     0,    28,    29,    32,
     0,     0,     0,    15,     7,    33,     8,     9,    28,    10,
    29,    29,    31,     0,    15,    33,     1,    10,     0,    15,
     7,    33,     9,     1,    10,     0,    13,     9,    29,    28,
    10,     0,     0,    16,     7,    33,     8,    29,    29,     9,
    28,    10,     0,    16,    33,     1,    10,     0,    16,     7,
    33,     9,     1,    13,     9,    28,    10,     0,    36,    12,
    36,     0,    34,     0,    27,    36,     0,    33,    17,    33,
     0,    33,    18,    33,     0,     1,     6,     0,     3,     5,
    36,     6,     0,     3,    11,     6,     0,     3,    14,     6,
     0,    11,     3,     6,     0,    14,     3,     6,     0,     1,
     0,    22,     0,    23,     0,    25,     0,    26,     0,    24,
     0,    36,    22,    36,     0,    36,    23,    36,     0,    36,
    20,    36,     0,    36,    24,    36,     0,    36,    25,    36,
     0,    36,    26,    36,     0,    36,    35,     0,    37,     0,
     3,    11,     0,     3,    14,     0,    11,     3,     0,    14,
     3,     0,     3,    38,     0,     4,    38,     0,     4,    11,
     1,     0,     4,    14,     1,     0,    14,     4,     1,     0,
    11,     4,     1,     0,     7,    36,     8,     0,     7,    36,
     1,     0,     3,     1,     0,     4,     1,     0,     0
};

#endif

#if (YY_parser_DEBUG != 0) || defined(YY_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   105,   108,   111,   114,   117,   123,   131,   141,   153,   155,
   158,   160,   170,   182,   189,   191,   195,   199,   203,   214,
   219,   223,   226,   229,   232,   241,   241,   241,   241,   241,
   243,   248,   253,   258,   263,   268,   279,   284,   291,   294,
   298,   302,   306,   309,   312,   320,   328,   336,   344,   348,
   357,   365,   374
};

static const char * const yytname[] = {   "$","error","$illegal.","VAR","Floats",
"ASSIGN","SC","LP","RP","CL","CR","INC","RELOP","Else","DEC","If","While","BoolAnd",
"BoolOr","'|'","'^'","'&'","'+'","'-'","'*'","'/'","'%'","'!'","S","M","IfStatement",
"ElseExpr","WhileStatements","BoolExp","Assignments","Op","Expr","Fact","C",
""
};
#endif

static const short yyr1[] = {     0,
    28,    28,    28,    28,    29,    30,    30,    30,    31,    31,
    32,    32,    32,    33,    33,    33,    33,    33,    33,    34,
    34,    34,    34,    34,    34,    35,    35,    35,    35,    35,
    36,    36,    36,    36,    36,    36,    36,    36,    37,    37,
    37,    37,    37,    37,    37,    37,    37,    37,    37,    37,
    38,    38,    38
};

static const short yyr2[] = {     0,
     3,     3,     3,     0,     0,    10,     4,     6,     5,     0,
     9,     4,     9,     3,     1,     2,     3,     3,     2,     4,
     3,     3,     3,     3,     1,     1,     1,     1,     1,     1,
     3,     3,     3,     3,     3,     3,     2,     1,     2,     2,
     2,     2,     2,     2,     3,     3,     3,     3,     3,     3,
     2,     2,     0
};

static const short yydefact[] = {     4,
     5,     0,    25,     0,     0,     0,     0,     0,     1,     3,
     2,     0,     0,     0,     0,     0,    25,    53,    53,     0,
     0,     0,     0,     0,    15,     0,    38,     0,     0,    53,
     0,     0,     0,     0,    21,    22,    23,    24,    19,     0,
     0,    39,    40,    43,     0,     0,    44,     0,     0,    41,
     0,    42,     0,    16,     0,     0,     0,     0,     0,    26,
    27,    30,    28,    29,    37,     0,     0,    39,    40,     0,
    41,    42,    20,    51,    52,    45,    46,     0,     0,    50,
    49,    48,    47,     7,    17,    18,    14,    33,    31,    32,
    34,    35,    36,     5,     0,    12,     4,     0,     5,     0,
     5,     8,     0,     0,     5,     4,     4,     5,     5,     5,
    10,    11,    13,     0,     6,     5,     4,     5,     9,     0,
     0
};

static const short yydefgoto[] = {     1,
     2,     9,   115,    10,    24,    25,    65,    26,    27,    44
};

static const short yypact[] = {-32768,
     7,    61,-32768,    55,     6,    26,    17,    29,-32768,-32768,
-32768,   121,    35,    53,    67,    83,    85,   101,    31,    54,
    10,    76,   121,     9,-32768,    97,-32768,    54,    21,   123,
   121,   107,   110,    77,-32768,-32768,-32768,-32768,-32768,    36,
    66,    35,    53,-32768,   115,   128,-32768,   122,    62,    67,
   135,    83,   142,   132,   134,    54,    54,   121,   121,   121,
   121,   121,   121,   121,-32768,   133,   136,-32768,-32768,    70,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   124,   144,-32768,
-32768,-32768,-32768,-32768,-32768,   130,   132,   137,   -22,   -22,
-32768,-32768,-32768,-32768,   147,-32768,-32768,   139,-32768,   125,
   143,-32768,   155,   156,-32768,-32768,-32768,-32768,   157,   158,
   153,-32768,-32768,   160,-32768,-32768,-32768,   161,-32768,   170,
-32768
};

static const short yypgoto[] = {     1,
   -93,-32768,-32768,-32768,    -3,   171,-32768,   -12,-32768,   159
};


#define	YYLAST		178


static const short yytable[] = {    34,
    99,    62,    63,    64,    29,   103,   120,    49,    15,    55,
    54,   108,    50,    51,   111,    49,    48,    17,    70,    18,
    19,    67,   117,    20,    66,    56,    57,    21,    16,    17,
    22,    18,    19,    40,    41,    28,    74,    56,    57,    21,
    35,    45,    22,    23,    46,    87,    88,    89,    90,    91,
    92,    93,    85,    86,    17,    23,    18,    19,    36,    12,
    31,     3,    80,     4,    21,    13,    75,    22,    14,    81,
    80,     5,    37,    58,     6,     7,     8,    81,    52,    53,
    23,    59,    73,    60,    61,    62,    63,    64,    38,    59,
    39,    60,    61,    62,    63,    64,    59,   101,    60,    61,
    62,    63,    64,    40,    41,    12,   109,   110,    58,    71,
    51,    42,    72,    53,    43,    76,    59,   118,    60,    61,
    62,    63,    64,    30,    19,    40,    41,    31,    77,    78,
    79,    32,    97,    68,    33,    82,    69,   104,    56,    57,
    94,    95,    83,    84,    98,    96,    56,   100,   102,    56,
    57,    59,   105,    60,    61,    62,    63,    64,    60,    61,
    62,    63,    64,   106,   107,   114,   112,   113,   116,   121,
   119,     0,    11,     0,     0,     0,     0,    47
};

static const short yycheck[] = {    12,
    94,    24,    25,    26,     8,    99,     0,    20,     3,     1,
    23,   105,     3,     4,   108,    28,    20,     1,    31,     3,
     4,     1,   116,     7,    28,    17,    18,    11,     3,     1,
    14,     3,     4,     3,     4,     7,     1,    17,    18,    11,
     6,    11,    14,    27,    14,    58,    59,    60,    61,    62,
    63,    64,    56,    57,     1,    27,     3,     4,     6,     5,
     7,     1,     1,     3,    11,    11,     1,    14,    14,     8,
     1,    11,     6,    12,    14,    15,    16,     8,     3,     4,
    27,    20,     6,    22,    23,    24,    25,    26,     6,    20,
     6,    22,    23,    24,    25,    26,    20,    97,    22,    23,
    24,    25,    26,     3,     4,     5,   106,   107,    12,     3,
     4,    11,     3,     4,    14,     1,    20,   117,    22,    23,
    24,    25,    26,     3,     4,     3,     4,     7,     1,     8,
     9,    11,     9,    11,    14,     1,    14,    13,    17,    18,
     8,     9,     1,    10,     1,    10,    17,     1,    10,    17,
    18,    20,    10,    22,    23,    24,    25,    26,    22,    23,
    24,    25,    26,     9,     9,    13,    10,    10,     9,     0,
    10,    -1,     2,    -1,    -1,    -1,    -1,    19
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_CHAR = (token), YY_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_PURE
/* UNPURE */
#define YYLEX           YY_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_CHAR;                      /*  the lookahead symbol        */
YY_parser_STYPE      YY_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_LSP_NEEDED
YY_parser_LTYPE YY_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_LSP_NEEDED
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL, &YY_parser_LLOC)
#else
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_DEBUG != 0
int YY_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_CLASS::
#endif
     YY_parser_PARSE(YY_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_LTYPE *yyls = yylsa;
  YY_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_PURE
  int YY_parser_CHAR;
  YY_parser_STYPE YY_parser_LVAL;
  int YY_parser_NERRS;
#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE YY_parser_LLOC;
#endif
#endif

  YY_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_NERRS = 0;
  YY_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_LSP_NEEDED
      YY_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_LSP_NEEDED
      yyls = (YY_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_CHAR == YYEMPTY)
    {
#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_CHAR);

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_CHAR, YY_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_CHAR != YYEOF)
    YY_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 105 "prob.y"
{ 
        
    ;
    break;}
case 2:
#line 108 "prob.y"
{
        
    ;
    break;}
case 3:
#line 111 "prob.y"
{ 
        
    ;
    break;}
case 4:
#line 114 "prob.y"
{;
    break;}
case 5:
#line 117 "prob.y"
{
        List* curr = yyval.list;
        curr->addr = lineNumber;
    ;
    break;}
case 6:
#line 124 "prob.y"
{
        List* B = yyvsp[-7].list;
        List* M1 = yyvsp[-2].list;
        List* M2 = yyvsp[-1].list;
        BackPatch(B->tlist,M1->addr);
        BackPatch(B->flist,M2->addr);
    ;
    break;}
case 7:
#line 133 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].list);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 8:
#line 143 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-3].list);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 9:
#line 154 "prob.y"
{   ;
    break;}
case 10:
#line 155 "prob.y"
{;
    break;}
case 11:
#line 159 "prob.y"
{;
    break;}
case 12:
#line 162 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].list);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 13:
#line 172 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-6].list);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 14:
#line 183 "prob.y"
{
        char* Label = getLabels();
        sprintf(interMedCode[instrPtr++],"%d %s = (%s %s %s);\n",lineNumber,Label,yyvsp[-2].list->val,yyvsp[-1].str,yyvsp[0].list->val);
        yyval.list->val = Label; yyval.list->tlist = NULL;
        yyval.list->addr = lineNumber++; yyval.list->tlist = NULL;
    ;
    break;}
case 15:
#line 190 "prob.y"
{;
    break;}
case 16:
#line 192 "prob.y"
{
        
    ;
    break;}
case 17:
#line 196 "prob.y"
{
        
    ;
    break;}
case 18:
#line 200 "prob.y"
{
        
    ;
    break;}
case 19:
#line 204 "prob.y"
{
        yyerror("");
        printf("\t\tBoolean Expression Issues\n\n");
        yyerrok;
        yyclearin;
        eflag = 3;
        handleClear(1);
    ;
    break;}
case 20:
#line 216 "prob.y"
{   
        
    ;
    break;}
case 21:
#line 220 "prob.y"
{ 
        
    ;
    break;}
case 22:
#line 223 "prob.y"
{ 
        
    ;
    break;}
case 23:
#line 226 "prob.y"
{ 
        
    ;
    break;}
case 24:
#line 229 "prob.y"
{ 
        
    ;
    break;}
case 25:
#line 232 "prob.y"
{
        yyerror("");
        printf("Missing \';\' or some syntax issue you have chanted ;) :) \n");
        yyerrok;
        yyclearin;
        handleClear(1);
    ;
    break;}
case 31:
#line 244 "prob.y"
{ 
        // Generate TAC for addition
        
    ;
    break;}
case 32:
#line 249 "prob.y"
{ 
        // Generate TAC for subtraction
        
    ;
    break;}
case 33:
#line 254 "prob.y"
{ 
        // Generate TAC for or
        
    ;
    break;}
case 34:
#line 259 "prob.y"
{ 
        // Generate TAC for multiplication
        
    ;
    break;}
case 35:
#line 264 "prob.y"
{   
        // Generate TAC for division
        
    ;
    break;}
case 36:
#line 269 "prob.y"
{
        if (strchr(yyvsp[-2].list, '.') == NULL && strchr(yyvsp[0].list, '.') == NULL)
        {
            
        }
        else
        {
            eflag = 1;  
        }
    ;
    break;}
case 37:
#line 281 "prob.y"
{
        eflag=2;
    ;
    break;}
case 38:
#line 285 "prob.y"
{
        yyval.list = strdup(yyvsp[0].list);
    ;
    break;}
case 39:
#line 291 "prob.y"
{ 
            // $$ = Label;
        ;
    break;}
case 40:
#line 294 "prob.y"
{ 
            
            // $$ = Label;
        ;
    break;}
case 41:
#line 298 "prob.y"
{ 
            
            // $$ = Label;
        ;
    break;}
case 42:
#line 302 "prob.y"
{ 
            
            // $$ = Label;
        ;
    break;}
case 43:
#line 306 "prob.y"
{ 
            
        ;
    break;}
case 44:
#line 309 "prob.y"
{ 
            
        ;
    break;}
case 45:
#line 313 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 46:
#line 321 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 47:
#line 329 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 48:
#line 337 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 49:
#line 345 "prob.y"
{ 
            yyval.list = strdup(yyvsp[-1].list); 
        ;
    break;}
case 50:
#line 349 "prob.y"
{
            yyerror("");
            printf("\t\tno ) detected after (\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 51:
#line 358 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 52:
#line 367 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_LLOC.first_line;
      yylsp->first_column = YY_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_NERRS;

#ifdef YY_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_ERROR_VERBOSE */
	YY_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_CHAR == YYEOF)
	YYABORT;

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_CHAR, yytname[yychar1]);
#endif

      YY_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 375 "prob.y"

int yyerror(char* err) {
    return 0;
}

int main(int argc, char* argv[]) {
    int yydebug = 1;
    interMedCode = (char**)malloc(1000*sizeof(char*));//map of lineNumber vs L
    handleClear(1);
    // Rest of the main function
    if (argc > 1) {
        FILE* inp = fopen(argv[1], "r");
        if (inp != NULL) {
            yyin = inp;
        } else {
            fprintf(stderr, "Failed to open file: %s\n", argv[1]);
            return 1;
        }
    }
    yyparse();
    fclose(yyin);

    //handleClear(1); // Clean up before exiting
    return 0;
}
