#define YY_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prob.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prob.y"

    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    #include "y.tab.h"
    #define SIZE 100
    #define TABLE_SIZE 100
    int yyerror(char*);
    extern FILE* yyin;
    int eflag = 0;  // Error flag for certain expressions
    extern int yylex();
    int yydebug = 0;
    int wentInArray=0;
    int blockVar =0;
    int IFCOUNTER=0;
    int tempVar=0;
    char* allocations[1000];
    int allocated=0;
    int ifStmntPtr=0;
    int lineNumber=1;
    int forIncrementer;
    char* array;
    char* type;


    //////////////////////////////////////////// SYMBOL TABLE BEGIN /////////////////////////////////////////////////////////////////
    typedef struct SymbolNode {
        char *token;
        char *type;
        int size;
        struct SymbolNode *next;
    } SyNode;

    typedef struct SymbolTable {
        SyNode* table[TABLE_SIZE];
        int size;
    } SymTable;

    void * createSymbTable(){
        
        SymTable *STable = (SymTable *)malloc(sizeof(SymTable));
        if (!STable) {
            fprintf(stderr, "Memory allocation failed\n");
            return NULL;
        }
        for (int i = 0; i < TABLE_SIZE; i++) {
            STable->table[i] = NULL;
        }
        STable->size = 0;
        return STable;
    }

    void Sinsert(SymTable *Stable,char *token, char *type) {
        int size =0;
        if(strcmp(type,"int")==0)
        {
            size=4;
        }
        else if(strcmp(type,"float")==0)
        {
            size=8;
        }
        else
        {
            size=1;
        }
        if(Stable->size < TABLE_SIZE)
        {
            SyNode* new_node = (SyNode*)malloc(sizeof(SyNode));
            new_node->size = size;
            new_node->token = strdup(token);
            new_node->type = strdup(type);
            Stable->table[Stable->size] = new_node;
            Stable->size++;
        }
        else
        {
            printf("Symbol Table out of Space!!!\n");
        }
    }

    void Sprint(SymTable * Stable)
    {
        printf("////////////////////////// SYMBOL TABLE //////////////////////////\n");
        
        // Define the width for each column for better alignment
        const int addr_width = 8;
        const int token_width = 20;
        const int type_width = 15;
        
        // Print the header row
        printf("%-*s%-*s%-*s\n", addr_width, "Addr", token_width, "Token", type_width, "Type");

        int n = Stable->size;
        int size = 0;

        // Iterate through the symbol table and print the entries
        for (int i = 0; i < n; i++) {
            printf("%-*d%-*s%-*s\n", addr_width, size, token_width, Stable->table[i]->token, type_width, Stable->table[i]->type);
            size += Stable->table[i]->size;
        }
        
        printf("//////////////////////////// END SYMBOL TABLE ////////////////////////\n");
    }
//////////////////////////////////////////// SYMBOL TABLE  END /////////////////////////////////////////////////////////////////

//////////////////////////////////////////// HASH MAP BEGIN /////////////////////////////////////////////////////////////////

    typedef struct Node {
        char *key;
        char *value;
        struct Node *next;
    } Node;

    // Hash map structure
    typedef struct HashMap {
        Node *table[TABLE_SIZE];
        int size;
    } HashMap;

    // Free all memory used by the hash map
    void free_hashmap(HashMap *map) {
        if (map == NULL) return;
        for (int i = 0; i < TABLE_SIZE; i++) {
            Node *current = map->table[i];
            while (current != NULL) {
                Node *temp = current;
                current = current->next;
                free(temp);
            }
            map->table[i] = NULL;  // Nullify after free
        }
        free(map);
    }

    // Hash function for strings
    unsigned int hash(const char *key) {
        unsigned long int hash_value = 0;
        int i = 0;

        while (key[i] != '\0') {
            hash_value = hash_value * 37 + key[i];
            i++;
        }

        return hash_value % TABLE_SIZE;
    }

    // Initialize hash map
    HashMap* create_hashmap() {
        HashMap *map = (HashMap *)malloc(sizeof(HashMap));
        if (!map) {
            fprintf(stderr, "Memory allocation failed\n");
            return NULL;
        }
        for (int i = 0; i < TABLE_SIZE; i++) {
            map->table[i] = NULL;
        }
        map->size = 0;
        return map;
    }

    // Create a new node for the hash map
    Node *create_node(const char *key, const char *value) {
        Node *new_node = (Node *)malloc(sizeof(Node));
        new_node->key = key;      // Copy key string
        new_node->value = value;  // Copy value string
        new_node->next = NULL;
        return new_node;
    }

    // Insert a key-value pair into the hash map
    void insert(HashMap *map,char *key, char *value) {
        unsigned int index = hash(key);
        Node *new_node = create_node(key, value);
        new_node->next = map->table[index];
        map->table[index] = new_node;
        map->size++;
    }

    // Search for a value by key in the hash map
    char *search(HashMap *map, const char *key) {
        unsigned int index = hash(key);
        Node *current = map->table[index];

        while (current != NULL) {
            if (strcmp(current->key, key) == 0) {
                return current->value;
            }
            current = current->next;
        }

        return NULL;  // Key not found
    }

    // Delete a key-value pair from the hash map
    void delete_key(HashMap *map, const char *key) {
        unsigned int index = hash(key);
        Node *current = map->table[index];
        Node *prev = NULL;

        while (current != NULL && strcmp(current->key, key) != 0) {
            prev = current;
            current = current->next;
        }

        if (current == NULL) return;  // Key not found

        if (prev == NULL) {  // Key is in the first node
            map->table[index] = current->next;
        } else {
            prev->next = current->next;
        }
        map->size--;
        free(current);
    }
//////////////////////////////////////////// HASH MAP END /////////////////////////////////////////////////////////////////

//////////////////////////////////////////// STACK BEGIN /////////////////////////////////////////////////////////////////


    // Stack node definition
    typedef struct StackNode {
        HashMap *map;
        struct StackNode *next;
    } StackNode;

    // Stack structure
    typedef struct Stack {
        StackNode *top;
        int size;
    } Stack;
    // Function to create a new stack
    Stack *create_stack() {
        Stack *stack = (Stack *)malloc(sizeof(Stack));
        stack->top = NULL;
        stack->size = 0;
        return stack;
    }

    // Push a hash map onto the stack
    void push(Stack *stack, HashMap *map) {
        StackNode *new_node = (StackNode *)malloc(sizeof(StackNode));
        new_node->map = map;
        new_node->next = stack->top;
        stack->top = new_node;
        stack->size++;
    }

    // Pop a hash map from the stack
    HashMap *pop(Stack *stack) {
        if (stack->top == NULL) {
            printf("Stack is empty!\n");
            return NULL;
        }

        StackNode *top_node = stack->top;
        HashMap *map = top_node->map;
        stack->top = top_node->next;
        free(top_node);
        stack->size--;
        return map;
    }

    // Peek at the top hash map without removing it
    HashMap *peek(Stack *stack) {
        if (stack->top == NULL) {
            printf("Stack is empty!\n");
            return NULL;
        }
        return stack->top->map;
    }

    // Check if the stack is empty
    int is_empty(Stack *stack) {
        return stack->top == NULL;
    }

    // Free the entire stack
    void free_stack(Stack *stack) {
        while (!is_empty(stack)) {
            HashMap *map = pop(stack);
            free_hashmap(map);  // Free each hash map in the stack
        }
        free(stack);
    }

//////////////////////////////////////////// STACK END //////////////////////////////////////////////////////////////////


    char* getLabels()
    {
        char* tVar = (char*)malloc(10*sizeof(char));
        snprintf(tVar,10,"t%d",tempVar++);
        allocations[allocated++] = tVar;
        return tVar;

    }
    void handleClear(int val)
    {
        lineNumber=1;
        ifStmntPtr=0;
        if(val)
        {
            tempVar=0;
            blockVar=0;
        }
    }

    Stack* globStack;
    HashMap* currMap;
    SymTable* SymbTable;
    void checkDeclaration(char* var, int newDecl)
    {
        Stack* tempStack = create_stack();
        if(newDecl && search(currMap,var)==NULL)
        {
            printf("%s type -> %s\n",var,type);
            array = var;
            Sinsert(SymbTable,var,type);//SymTable *Stable,char *token, char *type,int space
            insert(currMap,var,type);
            free_stack(tempStack);
            return;
        }
        while(!is_empty(globStack) && (search(currMap,var)==NULL))
        {
            push(tempStack, currMap);
            currMap = pop(globStack);
        }
        if((search(currMap,var)==NULL))
        {
            if(newDecl==0)
            {
                printf("Variable [`%s`]  not declared in all scopes\n",var);
                printf("I will add it anyways... sob sob weep weep\n");
                Sinsert(SymbTable,var,type);//SymTable *Stable,char *token, char *type,int space
            }
        }
        else if(newDecl)
        {
            char* val = search(currMap, var);
            printf("Error -> Redeclartion of variable [`%s`] !!\n",var);
            if(strcmp(val,type) !=0)
            {
                printf("Error -> Change of Type of variable [`%s`] !!\n",var);
                printf("I am a good compiler so I will change its type just like python\n");
                delete_key(currMap,var);
            }
        }
        else{
            //means type is defined....
            char* prevType = search(currMap,var);
            if(strcmp(prevType,type)!=0)
            {
                printf("%s = (%s)%s;\n", var,type,var);
            }
        }
        push(globStack,currMap);//put the currMap back...
        while(!is_empty(tempStack))
        {
            push(globStack,pop(tempStack));
        } 
        currMap = pop(globStack);//push in currMap...
        printf("%s type -> %s\n",var,type);
        array = var;
        insert(currMap,var,type);
        free_stack(tempStack);
    }


#line 373 "prob.y"
typedef union {
    char* str;
} yy_parser_stype;
#define YY_parser_STYPE yy_parser_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_BISON 1

#ifndef YY_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_COMPATIBILITY 1
 #else
  #define  YY_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_LTYPE
   #define YY_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_STYPE 
   #define YY_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_DEBUG
   #define  YY_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_USE_GOTO
  #define YY_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_USE_GOTO
 #define YY_parser_USE_GOTO 0
#endif

#ifndef YY_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parser_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_DEBUG */
#endif


#ifndef YY_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_LSP_NEEDED
#ifndef YY_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_STYPE
#define YY_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_PARSE
#define YY_parser_PARSE yyparse
#endif
#ifndef YY_parser_LEX
#define YY_parser_LEX yylex
#endif
#ifndef YY_parser_LVAL
#define YY_parser_LVAL yylval
#endif
#ifndef YY_parser_LLOC
#define YY_parser_LLOC yylloc
#endif
#ifndef YY_parser_CHAR
#define YY_parser_CHAR yychar
#endif
#ifndef YY_parser_NERRS
#define YY_parser_NERRS yynerrs
#endif
#ifndef YY_parser_DEBUG_FLAG
#define YY_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_ERROR
#define YY_parser_ERROR yyerror
#endif

#ifndef YY_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_PARSE_PARAM
  #define YY_parser_PARSE_PARAM void
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_PURE
#  endif
#endif

#ifdef YY_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_DEBUG 
#  endif
#endif

#ifndef YY_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	VAR	258
#define	Floats	259
#define	ASSIGN	260
#define	SC	261
#define	LP	262
#define	RP	263
#define	CL	264
#define	CR	265
#define	INC	266
#define	RELOP	267
#define	Else	268
#define	DEC	269
#define	Int	270
#define	If	271
#define	While	272
#define	BoolAnd	273
#define	BoolOr	274
#define	Float	275
#define	Char	276
#define	COMMA	277
#define	arrRP	278
#define	arrLP	279
#define	For	280


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_CLASS
#define YY_parser_CLASS parser
#endif
#ifndef YY_parser_INHERIT
#define YY_parser_INHERIT
#endif
#ifndef YY_parser_MEMBERS
#define YY_parser_MEMBERS 
#endif
#ifndef YY_parser_LEX_BODY
#define YY_parser_LEX_BODY  
#endif
#ifndef YY_parser_ERROR_BODY
#define YY_parser_ERROR_BODY  
#endif
#ifndef YY_parser_CONSTRUCTOR_PARAM
#define YY_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_CONSTRUCTOR_CODE
#define YY_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_CONSTRUCTOR_INIT
#define YY_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_USE_CONST_TOKEN
#define YY_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_USE_CONST_TOKEN != 0
#ifndef YY_parser_ENUM_TOKEN
#define YY_parser_ENUM_TOKEN yy_parser_enum_token
#endif
#endif

class YY_parser_CLASS YY_parser_INHERIT
{
public: 
#if YY_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int VAR;
static const int Floats;
static const int ASSIGN;
static const int SC;
static const int LP;
static const int RP;
static const int CL;
static const int CR;
static const int INC;
static const int RELOP;
static const int Else;
static const int DEC;
static const int Int;
static const int If;
static const int While;
static const int BoolAnd;
static const int BoolOr;
static const int Float;
static const int Char;
static const int COMMA;
static const int arrRP;
static const int arrLP;
static const int For;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_ENUM_TOKEN { YY_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,VAR=258
	,Floats=259
	,ASSIGN=260
	,SC=261
	,LP=262
	,RP=263
	,CL=264
	,CR=265
	,INC=266
	,RELOP=267
	,Else=268
	,DEC=269
	,Int=270
	,If=271
	,While=272
	,BoolAnd=273
	,BoolOr=274
	,Float=275
	,Char=276
	,COMMA=277
	,arrRP=278
	,arrLP=279
	,For=280


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_PARSE (YY_parser_PARSE_PARAM);
 virtual void YY_parser_ERROR(char *msg) YY_parser_ERROR_BODY;
#ifdef YY_parser_PURE
#ifdef YY_parser_LSP_NEEDED
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL,YY_parser_LTYPE *YY_parser_LLOC) YY_parser_LEX_BODY;
#else
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL) YY_parser_LEX_BODY;
#endif
#else
 virtual int YY_parser_LEX() YY_parser_LEX_BODY;
 YY_parser_STYPE YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
 YY_parser_LTYPE YY_parser_LLOC;
#endif
 int   YY_parser_NERRS;
 int    YY_parser_CHAR;
#endif
#if YY_parser_DEBUG != 0
 int YY_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM);
public:
 YY_parser_MEMBERS 
};
/* other declare folow */
#if YY_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_CLASS::VAR=258;
const int YY_parser_CLASS::Floats=259;
const int YY_parser_CLASS::ASSIGN=260;
const int YY_parser_CLASS::SC=261;
const int YY_parser_CLASS::LP=262;
const int YY_parser_CLASS::RP=263;
const int YY_parser_CLASS::CL=264;
const int YY_parser_CLASS::CR=265;
const int YY_parser_CLASS::INC=266;
const int YY_parser_CLASS::RELOP=267;
const int YY_parser_CLASS::Else=268;
const int YY_parser_CLASS::DEC=269;
const int YY_parser_CLASS::Int=270;
const int YY_parser_CLASS::If=271;
const int YY_parser_CLASS::While=272;
const int YY_parser_CLASS::BoolAnd=273;
const int YY_parser_CLASS::BoolOr=274;
const int YY_parser_CLASS::Float=275;
const int YY_parser_CLASS::Char=276;
const int YY_parser_CLASS::COMMA=277;
const int YY_parser_CLASS::arrRP=278;
const int YY_parser_CLASS::arrLP=279;
const int YY_parser_CLASS::For=280;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_CLASS::token */
#endif
/*apres const  */
YY_parser_CLASS::YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM) YY_parser_CONSTRUCTOR_INIT
{
#if YY_parser_DEBUG != 0
YY_parser_DEBUG_FLAG=0;
#endif
YY_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		159
#define	YYFLAG		-32768
#define	YYNTBASE	35

#define YYTRANSLATE(x) ((unsigned)(x) <= 280 ? yytranslate[x] : 67)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    34,     2,     2,     2,    33,    28,     2,     2,
     2,    31,    29,     2,    30,     2,    32,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    27,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    26,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25
};

#if YY_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     5,     6,    11,    12,    16,    17,    21,    22,
    26,    27,    28,    35,    36,    38,    40,    42,    44,    48,
    52,    53,    57,    59,    61,    62,    63,    74,    79,    86,
    91,    92,    93,    94,   108,   109,   118,   123,   133,   137,
   139,   142,   146,   150,   154,   159,   162,   164,   166,   168,
   170,   172,   176,   180,   184,   188,   192,   196,   199,   201,
   203,   204,   208,   211,   215,   219,   223,   227,   231,   235,
   238,   241,   244,   247,   249,   252,   255,   260
};

static const short yyrhs[] = {    -1,
    49,    36,    35,     0,     0,    48,     6,    37,    35,     0,
     0,    56,    38,    35,     0,     0,    53,    39,    35,     0,
     0,    45,    40,    35,     0,     0,     0,     9,    41,    35,
    10,    42,    35,     0,     0,    15,     0,    20,     0,    21,
     0,    43,     0,    44,    46,     6,     0,    46,    22,     3,
     0,     0,     3,    47,    65,     0,    59,     0,    64,     0,
     0,     0,    16,     7,    58,     8,     9,    50,    35,    10,
    51,    52,     0,    16,    58,     1,    10,     0,    16,     7,
    58,     9,     1,    10,     0,    13,     9,    35,    10,     0,
     0,     0,     0,    54,    25,     7,    48,     6,    58,     6,
    55,    48,     8,     9,    35,    10,     0,     0,    17,     7,
    58,     8,     9,    57,    35,    10,     0,    17,    58,     1,
    10,     0,    17,     7,    58,     9,     1,    13,     9,    35,
    10,     0,    61,    12,    61,     0,    59,     0,    34,    61,
     0,    58,    18,    58,     0,    58,    19,    58,     0,     3,
     5,    61,     0,    44,     3,     5,    61,     0,     1,     6,
     0,    29,     0,    30,     0,    32,     0,    33,     0,    31,
     0,    61,    29,    61,     0,    61,    30,    61,     0,    61,
    27,    61,     0,    61,    31,    61,     0,    61,    32,    61,
     0,    61,    33,    61,     0,    61,    60,     0,    62,     0,
    64,     0,     0,     3,    63,    65,     0,     4,    65,     0,
     4,    11,     1,     0,     4,    14,     1,     0,    14,     4,
     1,     0,    11,     4,     1,     0,     7,    61,     8,     0,
     7,    61,     1,     0,     3,    11,     0,     3,    14,     0,
    11,     3,     0,    14,     3,     0,    66,     0,     3,     1,
     0,     4,     1,     0,    24,     4,    23,    66,     0,     0
};

#endif

#if (YY_parser_DEBUG != 0) || defined(YY_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   393,   421,   421,   424,   424,   427,   427,   430,   430,   434,
   434,   437,   448,   448,   451,   456,   460,   466,   470,   476,
   480,   483,   484,   488,   494,   502,   506,   506,   516,   528,
   530,   532,   538,   544,   550,   557,   561,   571,   583,   589,
   590,   595,   600,   607,   616,   625,   634,   634,   634,   634,
   634,   636,   643,   650,   657,   664,   671,   684,   689,   695,
   696,   704,   704,   710,   718,   726,   734,   742,   746,   756,
   763,   770,   777,   785,   792,   801,   812,   870
};

static const char * const yytname[] = {   "$","error","$illegal.","VAR","Floats",
"ASSIGN","SC","LP","RP","CL","CR","INC","RELOP","Else","DEC","Int","If","While",
"BoolAnd","BoolOr","Float","Char","COMMA","arrRP","arrLP","For","'|'","'^'",
"'&'","'+'","'-'","'*'","'/'","'%'","'!'","S","@1","@2","@3","@4","@5","@6",
"@7","DeclType","TypeDecl","VarDecl","L","@8","MegAssign","IfStatement","@9",
"@10","ElseExpr","ForStatements","@11","@12","WhileStatements","@13","BoolExp",
"Assignments","Op","Expr","Fact","@14","Increments","C","Arrays",""
};
#endif

static const short yyr1[] = {     0,
    36,    35,    37,    35,    38,    35,    39,    35,    40,    35,
    41,    42,    35,    35,    43,    43,    43,    44,    45,    46,
    47,    46,    48,    48,    50,    51,    49,    49,    49,    52,
    52,    54,    55,    53,    57,    56,    56,    56,    58,    58,
    58,    58,    58,    59,    59,    59,    60,    60,    60,    60,
    60,    61,    61,    61,    61,    61,    61,    61,    61,    62,
    63,    62,    62,    62,    62,    62,    62,    62,    62,    64,
    64,    64,    64,    65,    65,    65,    66,    66
};

static const short yyr2[] = {     0,
     0,     3,     0,     4,     0,     3,     0,     3,     0,     3,
     0,     0,     6,     0,     1,     1,     1,     1,     3,     3,
     0,     3,     1,     1,     0,     0,    10,     4,     6,     4,
     0,     0,     0,    13,     0,     8,     4,     9,     3,     1,
     2,     3,     3,     3,     4,     2,     1,     1,     1,     1,
     1,     3,     3,     3,     3,     3,     3,     2,     1,     1,
     0,     3,     2,     3,     3,     3,     3,     3,     3,     2,
     2,     2,     2,     1,     2,     2,     4,     0
};

static const short yydefact[] = {     0,
     0,     0,    11,     0,     0,    15,     0,     0,    16,    17,
    18,     0,     9,     0,     1,     7,     0,     5,    23,    24,
    46,     0,    70,    71,     0,    72,    73,    61,    78,     0,
     0,     0,     0,     0,     0,    40,     0,    59,    60,     0,
     0,    21,     0,     0,     3,     0,     0,     0,     0,    61,
     0,    44,     0,    78,     0,     0,     0,     0,     0,    63,
    74,     0,     0,     0,     0,    41,     0,     0,     0,     0,
     0,     0,    47,    48,    51,    49,    50,    58,     0,     0,
     0,    78,    19,     0,    10,     0,     2,     8,     0,     6,
     0,    12,    62,    75,    76,    64,    65,     0,     0,     0,
    69,    68,    67,    66,    28,    42,    43,    39,    54,    52,
    53,    55,    56,    57,     0,     0,    37,    45,    22,    20,
     4,     0,     0,    78,    25,     0,    35,     0,     0,    13,
    77,     0,    29,     0,     0,     0,     0,     0,     0,    33,
    26,    36,     0,     0,    31,    38,     0,     0,    27,     0,
     0,     0,     0,     0,    30,    34,     0,     0,     0
};

static const short yydefgoto[] = {    53,
    46,    86,    49,    47,    44,    25,   123,    11,    12,    13,
    43,    82,    14,    15,   132,   145,   149,    16,    17,   144,
    18,   134,    35,    19,    78,    37,    38,    54,    39,    60,
    61
};

static const short yypact[] = {   221,
     6,   206,-32768,    23,    27,-32768,   146,   161,-32768,-32768,
-32768,    32,-32768,    16,-32768,-32768,    20,-32768,-32768,-32768,
-32768,   126,-32768,-32768,   242,-32768,-32768,   206,    10,   182,
    72,    84,   126,    52,    19,-32768,    87,-32768,-32768,   182,
    42,    49,     5,   198,-32768,   198,   198,    58,   198,    -6,
   126,   258,    48,    12,    69,    78,    92,    99,    97,-32768,
-32768,    94,    65,   103,   120,   258,    49,   114,   182,   182,
   126,   126,   126,   126,   126,   126,   126,-32768,   169,   115,
   126,    12,-32768,   123,-32768,   198,-32768,-32768,   263,-32768,
    51,-32768,-32768,-32768,-32768,-32768,-32768,   112,   132,   141,
-32768,-32768,-32768,-32768,-32768,-32768,   127,   258,   196,   -14,
   -14,-32768,-32768,-32768,   139,   153,-32768,   258,-32768,-32768,
-32768,   152,   198,   135,-32768,   159,-32768,   150,   182,-32768,
-32768,   242,-32768,   242,   162,    22,   160,   163,   242,-32768,
-32768,-32768,   164,   263,   166,-32768,   176,   181,-32768,   183,
   242,   242,   184,   190,-32768,-32768,   191,   204,-32768
};

static const short yypgoto[] = {     4,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,     2,-32768,
-32768,-32768,   -87,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    -7,    -1,-32768,    34,-32768,-32768,     0,   -51,
    81
};


#define	YYLAST		291


static const short yytable[] = {    20,
    41,   122,    93,   157,    23,    36,    36,    24,    34,    34,
    83,    21,    55,    56,    55,    56,    75,    76,    77,    68,
    57,    45,    62,    58,    20,    26,    84,   140,    36,    27,
   119,    34,    79,    59,    42,    59,    69,    70,    36,    69,
    70,    34,    80,    20,    48,    20,    20,    85,    20,    87,
    88,   101,    90,    81,    67,    52,   147,    92,   102,    69,
    70,   106,   107,    63,    89,   101,    66,    36,    36,    94,
    34,    34,   102,    63,    26,    64,    71,    72,    95,    73,
    74,    75,    76,    77,    91,    20,    27,    65,    20,   121,
    34,    72,    96,    73,    74,    75,    76,    77,    71,    97,
    98,    99,   100,   103,   108,   109,   110,   111,   112,   113,
   114,    69,    70,    72,   118,    73,    74,    75,    76,    77,
   104,   136,    20,   105,   117,   120,   130,    36,    50,    29,
    34,    20,    51,    20,   124,   137,    31,   138,    20,    32,
   125,   126,   143,    20,    69,    34,     1,   127,    28,    29,
    20,    20,    30,   128,   153,   154,    31,   129,    59,    32,
     6,     1,   135,    28,    29,     9,    10,    40,   133,   141,
   139,    31,   142,   146,    32,     6,   115,   116,   148,    33,
     9,    10,     1,   150,    28,    29,    69,    70,    51,   151,
   158,   152,    31,   155,    33,    32,     6,   -14,     1,   156,
     2,     9,    10,   159,   131,     0,     3,   -14,     4,     0,
    22,     5,     6,     7,     8,    33,    23,     9,    10,    24,
   -14,     1,   -32,     2,    73,    74,    75,    76,    77,     3,
     0,     4,     0,     0,     5,     6,     7,     8,     0,     0,
     9,    10,     1,     0,     2,   -32,     0,     0,     0,     0,
     3,   -14,     4,     0,     0,     5,     6,     7,     8,     0,
     0,     9,    10,     1,     0,     2,   -32,     0,     0,     0,
     0,     0,     0,     4,     0,     0,     5,     6,     0,     0,
     0,     0,     9,    10,    72,     0,    73,    74,    75,    76,
    77
};

static const short yycheck[] = {     0,
     8,    89,    54,     0,    11,     7,     8,    14,     7,     8,
     6,     6,     3,     4,     3,     4,    31,    32,    33,     1,
    11,     6,    30,    14,    25,     3,    22,     6,    30,     3,
    82,    30,    40,    24,     3,    24,    18,    19,    40,    18,
    19,    40,     1,    44,    25,    46,    47,    44,    49,    46,
    47,     1,    49,     5,     3,    22,   144,    10,     8,    18,
    19,    69,    70,    30,     7,     1,    33,    69,    70,     1,
    69,    70,     8,    40,     3,     4,    12,    27,     1,    29,
    30,    31,    32,    33,    51,    86,     3,     4,    89,    86,
    89,    27,     1,    29,    30,    31,    32,    33,    12,     1,
     4,     8,     9,     1,    71,    72,    73,    74,    75,    76,
    77,    18,    19,    27,    81,    29,    30,    31,    32,    33,
     1,   129,   123,    10,    10,     3,   123,   129,     3,     4,
   129,   132,     7,   134,    23,   132,    11,   134,   139,    14,
     9,     1,   139,   144,    18,   144,     1,     9,     3,     4,
   151,   152,     7,     1,   151,   152,    11,     6,    24,    14,
    15,     1,    13,     3,     4,    20,    21,     7,    10,    10,
     9,    11,    10,    10,    14,    15,     8,     9,    13,    34,
    20,    21,     1,     8,     3,     4,    18,    19,     7,     9,
     0,     9,    11,    10,    34,    14,    15,     0,     1,    10,
     3,    20,    21,     0,   124,    -1,     9,    10,    11,    -1,
     5,    14,    15,    16,    17,    34,    11,    20,    21,    14,
     0,     1,    25,     3,    29,    30,    31,    32,    33,     9,
    -1,    11,    -1,    -1,    14,    15,    16,    17,    -1,    -1,
    20,    21,     1,    -1,     3,    25,    -1,    -1,    -1,    -1,
     9,    10,    11,    -1,    -1,    14,    15,    16,    17,    -1,
    -1,    20,    21,     1,    -1,     3,    25,    -1,    -1,    -1,
    -1,    -1,    -1,    11,    -1,    -1,    14,    15,    -1,    -1,
    -1,    -1,    20,    21,    27,    -1,    29,    30,    31,    32,
    33
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_CHAR = (token), YY_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_PURE
/* UNPURE */
#define YYLEX           YY_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_CHAR;                      /*  the lookahead symbol        */
YY_parser_STYPE      YY_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_LSP_NEEDED
YY_parser_LTYPE YY_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_LSP_NEEDED
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL, &YY_parser_LLOC)
#else
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_DEBUG != 0
int YY_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_CLASS::
#endif
     YY_parser_PARSE(YY_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_LTYPE *yyls = yylsa;
  YY_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_PURE
  int YY_parser_CHAR;
  YY_parser_STYPE YY_parser_LVAL;
  int YY_parser_NERRS;
#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE YY_parser_LLOC;
#endif
#endif

  YY_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_NERRS = 0;
  YY_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_LSP_NEEDED
      YY_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_LSP_NEEDED
      yyls = (YY_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_CHAR == YYEMPTY)
    {
#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_CHAR);

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_CHAR, YY_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_CHAR != YYEOF)
    YY_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 393 "prob.y"
{ 
        if(eflag == 0) 
        {
            if(IFCOUNTER==1)
            {
                printf("\t\t Accepted!\n\n");
                printf("\nProcessing Next Input\n");
                tempVar=0;
                blockVar=0;
            }
            else
            {
                blockVar-=2;
            }
            IFCOUNTER--;
        }
        else if(eflag == 1)
        {
            printf("float not to be used with modulo symbol\n\n");
            handleClear(1);
        }
        else if( eflag==2)
        {
            printf("\t\t Operands not found\n\n");
            handleClear(1);
        }

    ;
    break;}
case 3:
#line 421 "prob.y"
{
        yyval.str = yyvsp[-1].str;
    ;
    break;}
case 5:
#line 424 "prob.y"
{ 
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 7:
#line 427 "prob.y"
{ 
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 9:
#line 431 "prob.y"
{
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 11:
#line 434 "prob.y"
{
        push(globStack,currMap);
        currMap = create_hashmap();
    ;
    break;}
case 12:
#line 437 "prob.y"
{
        yyval.str = yyvsp[-3].str;
        if(currMap!=NULL)
        {
            free_hashmap(currMap);
        }
        if(globStack->size>0)
        {
            currMap = pop(globStack);//restore old type info...
        }
    ;
    break;}
case 14:
#line 448 "prob.y"
{;
    break;}
case 15:
#line 453 "prob.y"
{
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 16:
#line 457 "prob.y"
{
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 17:
#line 461 "prob.y"
{
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 18:
#line 467 "prob.y"
{ type = yyvsp[0].str; ;
    break;}
case 19:
#line 471 "prob.y"
{
        yyval.str = "";
    ;
    break;}
case 20:
#line 477 "prob.y"
{
        checkDeclaration(yyvsp[0].str,1);
    ;
    break;}
case 21:
#line 480 "prob.y"
{
        checkDeclaration(yyvsp[0].str,1);
    ;
    break;}
case 23:
#line 485 "prob.y"
{
                yyval.str = yyvsp[0].str;
            ;
    break;}
case 24:
#line 489 "prob.y"
{
                yyval.str = yyvsp[0].str;
            ;
    break;}
case 25:
#line 495 "prob.y"
{
        printf("if t%d goto L%d\n goto L%d\n",tempVar-1,blockVar , blockVar+1);
        printf("L%d:\n",blockVar);
        free(yyvsp[-4].str);// a way to reduce mem leaks
        blockVar+=2;
        IFCOUNTER++;
        handleClear(0);
    ;
    break;}
case 26:
#line 502 "prob.y"
{   
        printf("L%d:\n",blockVar-1);
        handleClear(0);
    ;
    break;}
case 28:
#line 508 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 29:
#line 518 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-3].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 30:
#line 529 "prob.y"
{;
    break;}
case 31:
#line 530 "prob.y"
{;
    break;}
case 32:
#line 533 "prob.y"
{
        printf("L%d:\n",blockVar);
        forIncrementer = blockVar;
        blockVar++;
    ;
    break;}
case 33:
#line 538 "prob.y"
{
        printf("if t%d goto L%d\n goto L%d\n",tempVar-1,blockVar , blockVar+1); 
        printf("L%d:\n",blockVar);
        blockVar+=2;
        IFCOUNTER++;
        handleClear(0);
    ;
    break;}
case 34:
#line 544 "prob.y"
{
        printf("goto L%d\n",forIncrementer);
        handleClear(0);
    ;
    break;}
case 35:
#line 551 "prob.y"
{
        printf("if t%d goto L%d\n goto L%d\n", tempVar-1,blockVar , blockVar+1); 
        printf("L%d:\n",blockVar);
        blockVar+=2;
        IFCOUNTER++;
        handleClear(0);
    ;
    break;}
case 36:
#line 557 "prob.y"
{   
        printf("goto L%d\n",blockVar-2);
        handleClear(0);
    ;
    break;}
case 37:
#line 563 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \'(\' before %s \n\n",yyvsp[-2].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 38:
#line 573 "prob.y"
{
        yyerror("");
        printf("\t\t error : Expected \')\' after %s \n\n",yyvsp[-6].str);
        yyerrok;
        yyclearin;
        handleClear(1);
        eflag = 3;
    ;
    break;}
case 39:
#line 584 "prob.y"
{
        char* Label = getLabels();
        printf("%s = (%s %s %s);\n",Label,yyvsp[-2].str,yyvsp[-1].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 40:
#line 589 "prob.y"
{;
    break;}
case 41:
#line 590 "prob.y"
{
        char* Label = getLabels();
        printf("%s = ! ( %s );\n",Label,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 42:
#line 595 "prob.y"
{
        char* Label = getLabels();
        printf("%s =  (%s && %s) ;\n",Label,yyvsp[-2].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 43:
#line 600 "prob.y"
{
        char* Label = getLabels();
        printf("%s =  (%s || %s) ;\n",Label,yyvsp[-2].str,yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 44:
#line 609 "prob.y"
{   
        checkDeclaration(yyvsp[-2].str,0);
        char* Label = getLabels();
        printf("%s %s %s;\n",yyvsp[-2].str,yyvsp[-1].str,yyvsp[0].str);
        printf("%s = %s;\n",Label,yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 45:
#line 617 "prob.y"
{   
        checkDeclaration(yyvsp[-2].str,1);
        insert(currMap,yyvsp[-2].str,type);
        char* Label = getLabels();
        printf("%s %s %s %s;\n",type,yyvsp[-2].str,yyvsp[-1].str, yyvsp[0].str);
        printf("%s = %s;\n",Label,yyvsp[-2].str);
        yyval.str = Label;
    ;
    break;}
case 46:
#line 625 "prob.y"
{
        yyerror("");
        printf("Missing \';\' or some syntax issue you have chanted ;) :) \n");
        yyerrok;
        yyclearin;
        handleClear(1);
    ;
    break;}
case 52:
#line 637 "prob.y"
{ 
        // Generate TAC for addition
        char* Label = getLabels();
        printf("%s = %s + %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 53:
#line 644 "prob.y"
{ 
        // Generate TAC for subtraction
        char* Label = getLabels();
        printf("%s = %s - %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 54:
#line 651 "prob.y"
{ 
        // Generate TAC for or
        char* Label = getLabels();
        printf("%s = %s ^ %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 55:
#line 658 "prob.y"
{ 
        // Generate TAC for multiplication
        char* Label = getLabels();
        printf("%s = %s * %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 56:
#line 665 "prob.y"
{   
        // Generate TAC for division
        char* Label = getLabels();
        printf("%s = %s / %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
        yyval.str = Label;
    ;
    break;}
case 57:
#line 672 "prob.y"
{
        if (strchr(yyvsp[-2].str, '.') == NULL && strchr(yyvsp[0].str, '.') == NULL)
        {
            char* Label = getLabels();
            printf("%s = %s \% %s\n",Label, yyvsp[-2].str, yyvsp[0].str);
            yyval.str = Label;
        }
        else
        {
            eflag = 1;  
        }
    ;
    break;}
case 58:
#line 686 "prob.y"
{
        eflag=2;
    ;
    break;}
case 59:
#line 690 "prob.y"
{
        yyval.str = yyvsp[0].str;
    ;
    break;}
case 61:
#line 697 "prob.y"
{ 
            checkDeclaration(yyvsp[0].str,0);
            char* Label = getLabels();
            printf("%s = %s;\n",Label,yyvsp[0].str); 
            yyval.str = Label;
            array = yyvsp[0].str;
        ;
    break;}
case 63:
#line 704 "prob.y"
{ 
            char* Label = getLabels();
            printf("%s = %s;\n",Label,yyvsp[-1].str); 
            yyval.str = Label;
            array = NULL;
        ;
    break;}
case 64:
#line 711 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 65:
#line 719 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 66:
#line 727 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 67:
#line 735 "prob.y"
{
            yyerror("");
            printf("\t\tcannot increment a constant\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 68:
#line 743 "prob.y"
{ 
            yyval.str = yyvsp[-1].str; 
        ;
    break;}
case 69:
#line 747 "prob.y"
{
            yyerror("");
            printf("\t\tno ) detected after (\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 70:
#line 756 "prob.y"
{ 
                checkDeclaration(yyvsp[-1].str,0);
                char* Label = getLabels();
                printf("%s = %s\n",Label, yyvsp[-1].str);
                printf("%s = %s + 1\n",yyvsp[-1].str, yyvsp[-1].str);
                yyval.str = Label;
            ;
    break;}
case 71:
#line 763 "prob.y"
{ 
                checkDeclaration(yyvsp[-1].str,0);
                char* Label = getLabels();
                printf("%s = %s\n",Label, yyvsp[-1].str);
                printf("%s = %s - 1\n",yyvsp[-1].str, yyvsp[-1].str);
                yyval.str = Label;
            ;
    break;}
case 72:
#line 770 "prob.y"
{ 
                checkDeclaration(yyvsp[0].str,0);
                char* Label = getLabels();
                printf("%s = %s + 1\n",yyvsp[-1].str, yyvsp[-1].str);
                printf("%s = %s\n",Label, yyvsp[-1].str);
                yyval.str = Label;
            ;
    break;}
case 73:
#line 777 "prob.y"
{ 
                checkDeclaration(yyvsp[0].str,0);
                char* Label = getLabels();
                printf("%s = %s - 1\n",yyvsp[-1].str, yyvsp[-1].str);
                printf("%s = %s\n",Label, yyvsp[-1].str);
                yyval.str = Label;
            ;
    break;}
case 74:
#line 786 "prob.y"
{
            if(wentInArray)
            {
                printf("%s %s\n",array,yyvsp[0].str);
            }
        ;
    break;}
case 75:
#line 794 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 76:
#line 803 "prob.y"
{
            yyerror("");
            printf("\t\t no operators between Operands\n\n");
            yyerrok;
            yyclearin;
            handleClear(1);
        ;
    break;}
case 77:
#line 813 "prob.y"
{
            // Copy the original number
            if(array == NULL)
            {
                printf("Error -> Please dont use array operations with floats...!!!\n");
                yyval.str = "";
            }
            else{
                wentInArray = 1;
                char* number = yyvsp[-2].str;
                if (number == NULL) {
                    printf("Error: Memory allocation failed for 'number'.\n");
                    YYABORT; // or handle error
                }

                if (strchr(number, '.') != NULL) {
                    printf("Error: Using floats as array indices is not allowed!\nTruncating...to integer..\n");

                    // Find the position of the decimal point
                    char* dot_position = strchr(number, '.');
                    int int_part_length = dot_position - number;

                    // Allocate memory for the integer part
                    char* integer_part = (char*)malloc(int_part_length + 1);
                    if (integer_part != NULL) {
                        strncpy(integer_part, number, int_part_length);
                        integer_part[int_part_length] = '\0';

                        // Free original number and assign integer_part to number
                        free(number);
                        number = integer_part;
                    } else {
                        // On memory allocation failure, set number to "0"
                        free(number);
                        number = "0";
                        if (number == NULL) {
                            printf("Error: Memory allocation failed for '0'.\n");
                            YYABORT;
                        }
                    }
                }

                // Create the output string
                char* sending = (char*)malloc(20000);
                if (sending != NULL) {
                    sprintf(sending, "array(%s , %s)", number, yyvsp[0].str);
                    yyval.str = sending;
                } else {
                    printf("Error: Memory allocation failed for 'sending'.\n");
                    yyval.str = NULL;
                    YYABORT;
                }
                // Clean up
                free(number);    
            }
            
        ;
    break;}
case 78:
#line 870 "prob.y"
{
            yyval.str = "";
        ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_LLOC.first_line;
      yylsp->first_column = YY_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_NERRS;

#ifdef YY_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_ERROR_VERBOSE */
	YY_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_CHAR == YYEOF)
	YYABORT;

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_CHAR, yytname[yychar1]);
#endif

      YY_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 875 "prob.y"

int yyerror(char* err) {
    return 0;
}

int main(int argc, char* argv[]) {
    int yydebug = 1;
    globStack = create_stack();
    currMap = create_hashmap();
    SymbTable = createSymbTable();
    handleClear(1);
    // Rest of the main function
    if (argc > 1) {
        FILE* inp = fopen(argv[1], "r");
        if (inp != NULL) {
            yyin = inp;
        } else {
            fprintf(stderr, "Failed to open file: %s\n", argv[1]);
            return 1;
        }
    }
    for(int i=0;i<allocated;i++)
    {
        free(allocations[i]);
    }
    yyparse();
    Sprint(SymbTable);
    free(SymbTable);
    free_stack(globStack);
    fclose(yyin);

    //handleClear(1); // Clean up before exiting
    return 0;
}
